#!/usr/bin/env python3
"""
Agent Black — Remote Server Deployment Manager
Pulls pre-built images from GHCR (built by GitHub Actions CI/CD).
No source upload needed — just configure and pull.
"""

import paramiko
import sys
import os
import getpass
import textwrap


# ─── CONFIGURE THESE ───────────────────────────────────────────────────────────
HOST = os.environ.get("DEPLOY_HOST", "64.227.177.219")
USER = os.environ.get("DEPLOY_USER", "root")
# Password is prompted at runtime or set via DEPLOY_PASSWORD env var
PASSWORD = os.environ.get("DEPLOY_PASSWORD", "Do12345@Do")

DOMAIN = os.environ.get("DEPLOY_DOMAIN", "agentblack.hareeshworks.in")
EMAIL = os.environ.get("DEPLOY_EMAIL", "admin@agentblack.hareeshworks.in")

GITHUB_OWNER = os.environ.get("GITHUB_OWNER", "hareesh08")
GHCR_TOKEN = os.environ.get("GHCR_TOKEN", "")  # Only needed for private repos

PROJECT_NAME = "agent-black"
APP_DIR = f"/opt/{PROJECT_NAME}"
CONTROL_PANEL_PORT = 8000
FRONTEND_PORT = 8080
IMAGE_TAG = os.environ.get("IMAGE_TAG", "latest")

IMAGE_BASE = f"ghcr.io/{GITHUB_OWNER}/agent-black"

# ── API Keys: read from env vars or local .env file ─────────────────────────
def _load_local_env():
    """Read key=value pairs from the local .env file (project root)."""
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
    vals = {}
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                vals[k.strip()] = v.strip()
    return vals

_LOCAL_ENV = _load_local_env()

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", _LOCAL_ENV.get("OPENAI_API_KEY", ""))
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", _LOCAL_ENV.get("ANTHROPIC_API_KEY", ""))
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", _LOCAL_ENV.get("GEMINI_API_KEY", ""))

# ──────────────────────────────────────────────────────────────────────────────


def run(client, command, timeout=120, print_output=True):
    stdin, stdout, stderr = client.exec_command(command, timeout=timeout)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    code = stdout.channel.recv_exit_status()
    if print_output:
        log(command.split("\n")[0][:80], out, err, code)
    return code, out, err


def log(label, out, err, code):
    print(f"=== {label} ===")
    if out.strip():
        print(out.rstrip())
    if err.strip():
        print(err.rstrip())
    print(f"--- EXIT {code} ---")
    print()


def connect():
    pw = PASSWORD or getpass.getpass(f"Password for {USER}@{HOST}: ")
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(
        hostname=HOST,
        username=USER,
        password=pw,
        timeout=20,
        allow_agent=False,
        look_for_keys=False,
    )
    return client


# ─── FILE GENERATORS ──────────────────────────────────────────────────────────


def generate_compose_file():
    """Production docker-compose that pulls pre-built images from GHCR."""
    return textwrap.dedent(f"""\
        # Auto-generated by deploy-agent-black.py
        # Images: {IMAGE_BASE}/*:{IMAGE_TAG}
        services:
          research-agent:
            image: {IMAGE_BASE}/research-agent:{IMAGE_TAG}
            env_file: .env
            volumes:
              - agent-black-data:/app/data
            restart: unless-stopped
            healthcheck:
              test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
              interval: 30s
              timeout: 5s
              retries: 3
              start_period: 20s
            networks:
              - agent-black-net

          solution-agent:
            image: {IMAGE_BASE}/solution-agent:{IMAGE_TAG}
            env_file: .env
            volumes:
              - agent-black-data:/app/data
            restart: unless-stopped
            healthcheck:
              test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
              interval: 30s
              timeout: 5s
              retries: 3
              start_period: 20s
            networks:
              - agent-black-net

          experiment-agent:
            image: {IMAGE_BASE}/experiment-agent:{IMAGE_TAG}
            env_file: .env
            volumes:
              - agent-black-data:/app/data
            restart: unless-stopped
            healthcheck:
              test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"]
              interval: 30s
              timeout: 5s
              retries: 3
              start_period: 20s
            networks:
              - agent-black-net

          control-panel:
            image: {IMAGE_BASE}/control-panel:{IMAGE_TAG}
            ports:
              - "127.0.0.1:{CONTROL_PANEL_PORT}:{CONTROL_PANEL_PORT}"
            env_file: .env
            volumes:
              - agent-black-data:/app/data
            depends_on:
              research-agent:
                condition: service_healthy
              solution-agent:
                condition: service_healthy
              experiment-agent:
                condition: service_healthy
            restart: unless-stopped
            healthcheck:
              test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
              interval: 30s
              timeout: 5s
              retries: 3
              start_period: 30s
            networks:
              - agent-black-net

          frontend:
            image: {IMAGE_BASE}/frontend:{IMAGE_TAG}
            ports:
              - "127.0.0.1:{FRONTEND_PORT}:{FRONTEND_PORT}"
            env_file: .env
            depends_on:
              control-panel:
                condition: service_healthy
            restart: unless-stopped
            networks:
              - agent-black-net

        networks:
          agent-black-net:
            driver: bridge

        volumes:
          agent-black-data:
    """)


def detect_server_ip(client):
    """Auto-detect the VPS public IP from the server itself."""
    print(">>> Detecting server public IP...")
    code, out, err = run(client,
        "curl -fsS https://api.ipify.org 2>/dev/null || curl -fsS https://ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}'",
        timeout=15, print_output=False)
    ip = out.strip()
    if ip:
        print(f"    Server public IP: {ip}")
    else:
        ip = HOST  # fallback to the SSH connection host
        print(f"    Could not detect IP, falling back to HOST={ip}")
    return ip


def generate_env_file(server_ip=None, api_url=None):
    """Generate .env for production. Auto-sets VITE_API_URL from server IP."""
    ip = server_ip or HOST
    # If a custom domain is configured, use https+domain; otherwise use http+IP
    if DOMAIN and DOMAIN != ip:
        base_url = f"https://{DOMAIN}"
        api_url = api_url or f"https://{DOMAIN}/api"
    else:
        base_url = f"http://{ip}"
        api_url = api_url or f"http://{ip}:{CONTROL_PANEL_PORT}/api"

    return textwrap.dedent(f"""\
        # ── Agent Black Production Config (auto-generated) ────
        HOST=0.0.0.0
        PORT={CONTROL_PANEL_PORT}
        COMPOSE_PROJECT_NAME={PROJECT_NAME}

        # ── Environment ──────────────────────────────────────
        APP_ENV=production

        # ── Auto-detected URLs ────────────────────────────────
        SERVER_IP={ip}
        VITE_API_URL={api_url}

        # ── Agent URLs (Docker service names for internal networking) ──
        RESEARCH_AGENT_URL=http://research-agent:8001
        SOLUTION_AGENT_URL=http://solution-agent:8002
        EXPERIMENT_AGENT_URL=http://experiment-agent:8003
        HOST_AGENT_URL=http://control-panel:8000

        # ── Domain ────────────────────────────────────────────
        DOMAIN={DOMAIN}
        BASE_URL={base_url}
        FRONTEND_PORT={FRONTEND_PORT}

        # ── LLM API Keys (auto-injected from local config) ───
        OPENAI_API_KEY={OPENAI_API_KEY}
        ANTHROPIC_API_KEY={ANTHROPIC_API_KEY}
        GEMINI_API_KEY={GEMINI_API_KEY}
    """)


def generate_nginx_config():
    """Generate Nginx reverse-proxy config."""
    return textwrap.dedent(f"""\
        server {{
            listen 80;
            listen [::]:80;
            server_name {DOMAIN};

            # Frontend (TanStack Start)
            location / {{
                proxy_pass http://127.0.0.1:{FRONTEND_PORT};
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_buffering off;
                proxy_cache off;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
            }}

            # Control Panel API
            location /api/ {{
                proxy_pass http://127.0.0.1:{CONTROL_PANEL_PORT}/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_buffering off;
                proxy_cache off;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
            }}

            # SSE streaming endpoints
            location /api/query/stream/ {{
                proxy_pass http://127.0.0.1:{CONTROL_PANEL_PORT}/api/query/stream/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_buffering off;
                proxy_cache off;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
                chunked_transfer_encoding on;
            }}
        }}
    """)


def write_remote_file(client, remote_path, content):
    """Write a string to a file on the remote server via SFTP."""
    sftp = client.open_sftp()
    # Ensure parent directory exists
    parent = os.path.dirname(remote_path).replace("\\", "/")
    run(client, f"mkdir -p {parent}", print_output=False)
    with sftp.open(remote_path, "w") as f:
        f.write(content)
    sftp.close()


# ─── ACTIONS ──────────────────────────────────────────────────────────────────


def setup(client):
    """Full fresh deploy: Docker + Nginx + SSL + pull GHCR images."""

    # Step 1: Install Docker, Nginx, Certbot
    print(">>> Installing Docker, Nginx, Certbot...")
    bootstrap = textwrap.dedent("""\
        set -euo pipefail
        export DEBIAN_FRONTEND=noninteractive

        apt update
        apt install -y ca-certificates curl gnupg lsb-release openssl git ufw

        # Docker repo
        install -m 0755 -d /etc/apt/keyrings
        if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
        fi
        cat >/etc/apt/sources.list.d/docker.list <<EOF
        deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable
        EOF
        apt update
        apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        systemctl enable --now docker

        apt install -y nginx
        systemctl enable --now nginx

        apt install -y certbot python3-certbot-nginx
    """)
    run(client, bootstrap, timeout=600)

    # Step 2: Login to GHCR (for private repos)
    if GHCR_TOKEN:
        print(">>> Logging into GHCR...")
        run(client, f'echo "{GHCR_TOKEN}" | docker login ghcr.io -u "{GITHUB_OWNER}" --password-stdin')

    # Step 3: Auto-detect server IP
    server_ip = detect_server_ip(client)

    # Step 4: Write config files
    print(">>> Writing docker-compose.yml...")
    run(client, f"mkdir -p {APP_DIR}")
    write_remote_file(client, f"{APP_DIR}/docker-compose.yml", generate_compose_file())

    print(f">>> Writing .env file (VITE_API_URL auto-set for {server_ip})...")
    write_remote_file(client, f"{APP_DIR}/.env", generate_env_file(server_ip=server_ip))
    keys_injected = any([OPENAI_API_KEY, ANTHROPIC_API_KEY, GEMINI_API_KEY])
    if keys_injected:
        print("    API keys auto-injected from local .env")
    else:
        print(f"    WARNING: No API keys found! Add them to {APP_DIR}/.env on the server.")

    # Step 5: Pull images & start
    print(">>> Pulling images from GHCR and starting services...")
    run(client, f"""
set -euo pipefail
cd {APP_DIR}
docker compose down --remove-orphans 2>/dev/null || true
docker compose pull
docker compose up -d
echo ">>> Waiting for services..."
sleep 15
docker compose ps
""", timeout=600)

    # Step 6: Nginx
    print(">>> Configuring Nginx...")
    write_remote_file(client, "/etc/nginx/sites-available/agentblack", generate_nginx_config())
    run(client, """
set -euo pipefail
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/agentblack /etc/nginx/sites-enabled/agentblack
nginx -t
systemctl enable --now nginx
systemctl reload nginx
""")

    # Step 7: Firewall
    print(">>> Configuring firewall...")
    run(client, """
ufw allow 22/tcp || true
ufw allow 80/tcp || true
ufw allow 443/tcp || true
ufw --force enable
""")

    # Step 8: SSL
    print(">>> Obtaining SSL certificate...")
    run(client, f"""
certbot --nginx -d {DOMAIN} --email {EMAIL} --agree-tos --non-interactive || true
systemctl reload nginx
""", timeout=300)

    # Step 9: Health check
    print(">>> Running health checks...")
    run(client, f"""
echo "=== Docker Status ==="
cd {APP_DIR} && docker compose ps

echo ""
echo "=== Control Panel Health ==="
curl -fsS http://127.0.0.1:{CONTROL_PANEL_PORT}/health || echo "Control panel not responding"

echo ""
echo "=== Nginx Test ==="
nginx -t 2>&1

echo ""
echo "=== SSL Certs ==="
certbot certificates 2>/dev/null || true

echo ""
echo "=== Site ==="
curl -fsS -o /dev/null -w "HTTP Status: %{{http_code}}" https://{DOMAIN}/ || echo "Site not accessible yet"
""")

    print("\n" + "=" * 60)
    print(f"  DEPLOYMENT COMPLETE!")
    print(f"  Site URL  : https://{DOMAIN}")
    print(f"  API URL   : https://{DOMAIN}/api/")
    print(f"  Server    : {USER}@{HOST}")
    print(f"  Images    : {IMAGE_BASE}/*:{IMAGE_TAG}")
    print("=" * 60)
    print(f"\n  All done! No manual steps needed.")


def check_status(client):
    """Check server status."""
    commands = [
        ("Docker Service", "systemctl is-active docker"),
        ("Nginx Service", "systemctl is-active nginx"),
        ("Docker Containers", f"cd {APP_DIR} && docker compose ps 2>/dev/null || echo 'No compose project'"),
        ("Images", f"docker images '{IMAGE_BASE}/*' --format '{{{{.Repository}}}}:{{{{.Tag}}}} ({{{{.Size}}}})'"),
        ("Nginx Test", "nginx -t 2>&1 || true"),
        ("SSL Certs", "certbot certificates 2>/dev/null || true"),
        ("Control Panel", f"curl -fsS http://127.0.0.1:{CONTROL_PANEL_PORT}/health 2>/dev/null || echo 'not responding'"),
        ("Frontend", f"curl -fsS -o /dev/null -w 'HTTP %{{http_code}}' http://127.0.0.1:{FRONTEND_PORT}/ 2>/dev/null || echo 'not responding'"),
    ]
    for label, cmd in commands:
        run(client, cmd, timeout=30)


def update(client):
    """Pull latest images from GHCR, refresh config, and restart."""
    # Refresh config files (agent URLs, etc.)
    server_ip = detect_server_ip(client)
    print(">>> Refreshing docker-compose.yml and .env...")
    write_remote_file(client, f"{APP_DIR}/docker-compose.yml", generate_compose_file())
    write_remote_file(client, f"{APP_DIR}/.env", generate_env_file(server_ip=server_ip))

    # Clear stale agent URLs from SQLite so env vars take effect
    print(">>> Clearing stale agent URLs from database...")
    run(client, f"""
cd {APP_DIR}
docker compose exec -T control-panel python -c "
import sqlite3, os
db = sqlite3.connect('/app/data/agent_black_production.db')
for key in ['RESEARCH_AGENT_URL', 'SOLUTION_AGENT_URL', 'EXPERIMENT_AGENT_URL', 'HOST_AGENT_URL']:
    db.execute('DELETE FROM settings WHERE key=?', (key,))
db.commit()
db.close()
print('Cleared stale agent URLs')
" 2>/dev/null || echo "(DB clear skipped — will use env vars on fresh start)"
""", print_output=True)

    print(">>> Pulling latest images from GHCR...")
    code, out, err = run(client, f"""
set -euo pipefail
cd {APP_DIR}

echo ">>> Pulling new images..."
docker compose pull

echo ">>> Recreating containers with fresh config..."
docker compose up -d --force-recreate --remove-orphans

echo ">>> Waiting for healthy..."
sleep 15

echo ">>> Status:"
docker compose ps

echo ">>> Health:"
curl -fsS http://127.0.0.1:{CONTROL_PANEL_PORT}/health || echo "Control panel not responding"

echo ">>> Pruning old images..."
docker image prune -f || true
""", timeout=600)
    log("UPDATE COMPLETE", out, err, code)


def restart(client):
    """Restart all Docker containers and Nginx."""
    run(client, f"""
set -euo pipefail
cd {APP_DIR}

echo ">>> Restarting Docker containers..."
docker compose restart

echo ">>> Restarting Nginx..."
systemctl restart nginx

echo ">>> Status:"
docker compose ps
systemctl is-active docker nginx

echo ">>> Health:"
curl -fsS http://127.0.0.1:{CONTROL_PANEL_PORT}/health || echo "not responding"
""", timeout=300)


def view_logs(client):
    """View recent container logs."""
    run(client, f"""
cd {APP_DIR}
for svc in control-panel frontend research-agent solution-agent experiment-agent; do
    echo "=== $svc ==="
    docker compose logs --tail 20 $svc 2>/dev/null || echo "(no logs)"
    echo ""
done
echo "=== Nginx Error Log ==="
tail -20 /var/log/nginx/error.log 2>/dev/null || true
""", timeout=120)


def renew_ssl(client):
    """Renew SSL certificate."""
    run(client, """
set -euo pipefail
certbot certificates 2>/dev/null || true
certbot renew --non-interactive || true
nginx -t && systemctl reload nginx
certbot certificates 2>/dev/null || true
""", timeout=300)


def rollback(client):
    """Roll back to previous images (swap compose to 'previous' tag)."""
    print(">>> Rolling back to previous images...")
    # Show available tags
    run(client, f"""
echo "Available image tags:"
docker images '{IMAGE_BASE}/*' --format '{{{{.Repository}}}}:{{{{.Tag}}}}' | sort

echo ""
echo "Current running:"
cd {APP_DIR} && docker compose ps
""")
    print("To rollback, SSH into the server and edit docker-compose.yml to use a specific SHA tag.")
    print(f"  ssh {USER}@{HOST}")
    print(f"  cd {APP_DIR}")
    print(f"  sed -i 's/:latest/:<sha-tag>/g' docker-compose.yml")
    print(f"  docker compose up -d")


def fresh_rebuild(client):
    """Nuke everything and do a clean pull + start."""
    print(">>> WARNING: This removes all containers, images, and volumes!")
    confirm = input("  Type 'yes' to confirm: ").strip()
    if confirm != "yes":
        print("  Aborted.")
        return

    run(client, f"""
set -euo pipefail
cd {APP_DIR}

echo ">>> Stopping and removing everything..."
docker compose down --remove-orphans --volumes --timeout 10 2>/dev/null || true
docker images --format '{{{{.Repository}}}}:{{{{.Tag}}}}' | grep 'agent-black' | xargs -r docker rmi -f 2>/dev/null || true
docker system prune -af --volumes

echo ">>> Pulling fresh images..."
docker compose pull

echo ">>> Starting services..."
docker compose up -d

echo ">>> Waiting..."
sleep 15

echo ">>> Status:"
docker compose ps

echo ">>> Health:"
curl -fsS http://127.0.0.1:{CONTROL_PANEL_PORT}/health || echo "not responding"
""", timeout=600)


def shell(client):
    """Open an interactive SSH shell with useful aliases."""
    print(f">>> Opening SSH shell to {USER}@{HOST}")
    print(f"    Quick commands:")
    print(f"      cd {APP_DIR} && docker compose ps")
    print(f"      cd {APP_DIR} && docker compose logs -f")
    print(f"      cd {APP_DIR} && docker compose restart")
    print()

    channel = client.get_transport().open_session()
    channel.get_pty(width=120, height=40)
    channel.invoke_shell()

    import select
    try:
        while True:
            r, w, e = select.select([channel, sys.stdin], [], [], 1)
            if channel in r:
                data = channel.recv(4096)
                if not data:
                    break
                sys.stdout.buffer.write(data)
                sys.stdout.flush()
            if sys.stdin in r:
                data = sys.stdin.buffer.read1(4096)
                if not data:
                    break
                channel.send(data)
    except (EOFError, KeyboardInterrupt):
        pass
    finally:
        channel.close()


# ─── MAIN ─────────────────────────────────────────────────────────────────────


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    print("=" * 60)
    print("  AGENT BLACK — REMOTE DEPLOYMENT MANAGER (GHCR)")
    print("=" * 60)
    print(f"  Server   : {USER}@{HOST}")
    print(f"  Domain   : {DOMAIN}")
    print(f"  Images   : {IMAGE_BASE}/*:{IMAGE_TAG}")
    print(f"  App Dir  : {APP_DIR}")
    print("=" * 60)
    print()
    print("  1) setup          - Full deploy (Docker, Nginx, SSL, pull images)")
    print("  2) status         - Check server & container status")
    print("  3) update         - Pull latest GHCR images & restart (fast!)")
    print("  4) restart        - Restart all services")
    print("  5) logs           - View recent container logs")
    print("  6) ssl-renew      - Renew SSL certificate")
    print("  7) rollback       - Show image tags for manual rollback")
    print("  8) fresh-rebuild  - Nuke everything & clean pull")
    print("  9) shell          - Open interactive SSH shell")
    print()

    choice = input("  Enter choice (1-9): ").strip()

    actions = {
        "1": ("setup", setup),
        "2": ("status", check_status),
        "3": ("update", update),
        "4": ("restart", restart),
        "5": ("logs", view_logs),
        "6": ("ssl-renew", renew_ssl),
        "7": ("rollback", rollback),
        "8": ("fresh-rebuild", fresh_rebuild),
        "9": ("shell", shell),
    }

    if choice not in actions:
        print("  Invalid choice.")
        return

    action_name, action_fn = actions[choice]
    print(f"\n  Running: {action_name} ...\n")

    client = connect()
    try:
        action_fn(client)
    finally:
        client.close()
    print("\nDone.")


if __name__ == "__main__":
    main()
